(cl:defpackage pr2_msgs-srv
  (:use )
  (:export
   "SETPERIODICCMD"
   "<SETPERIODICCMD-REQUEST>"
   "SETPERIODICCMD-REQUEST"
   "<SETPERIODICCMD-RESPONSE>"
   "SETPERIODICCMD-RESPONSE"
   "SETLASERTRAJCMD"
   "<SETLASERTRAJCMD-REQUEST>"
   "SETLASERTRAJCMD-REQUEST"
   "<SETLASERTRAJCMD-RESPONSE>"
   "SETLASERTRAJCMD-RESPONSE"
  ))

