/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/viki/school/PTT7/new-launch/ESA-PROJ/esa_proj/src/fontys_at_work/denpendencies/pr2_common/pr2_msgs/srv/SetPeriodicCmd.srv
 *
 */


#ifndef PR2_MSGS_MESSAGE_SETPERIODICCMD_H
#define PR2_MSGS_MESSAGE_SETPERIODICCMD_H

#include <ros/service_traits.h>


#include <pr2_msgs/SetPeriodicCmdRequest.h>
#include <pr2_msgs/SetPeriodicCmdResponse.h>


namespace pr2_msgs
{

struct SetPeriodicCmd
{

typedef SetPeriodicCmdRequest Request;
typedef SetPeriodicCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPeriodicCmd
} // namespace pr2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pr2_msgs::SetPeriodicCmd > {
  static const char* value()
  {
    return "daeb6e862b732192bc82a7ea52bb7975";
  }

  static const char* value(const ::pr2_msgs::SetPeriodicCmd&) { return value(); }
};

template<>
struct DataType< ::pr2_msgs::SetPeriodicCmd > {
  static const char* value()
  {
    return "pr2_msgs/SetPeriodicCmd";
  }

  static const char* value(const ::pr2_msgs::SetPeriodicCmd&) { return value(); }
};


// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmdRequest> should match 
// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct MD5Sum< ::pr2_msgs::SetPeriodicCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_msgs::SetPeriodicCmdRequest> should match 
// service_traits::DataType< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct DataType< ::pr2_msgs::SetPeriodicCmdRequest>
{
  static const char* value()
  {
    return DataType< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmdResponse> should match 
// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct MD5Sum< ::pr2_msgs::SetPeriodicCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_msgs::SetPeriodicCmdResponse> should match 
// service_traits::DataType< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct DataType< ::pr2_msgs::SetPeriodicCmdResponse>
{
  static const char* value()
  {
    return DataType< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PR2_MSGS_MESSAGE_SETPERIODICCMD_H
